baseURL = "/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-universal-theme"
publishDir = "public"

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
Name = "about Us"
identifier = "about_us"
URL = "#"
weight = 1.0

[[menu.main]]
Name = "Who We Are"
parent = "about_us"
URL = "/about_us/who_we_are"
Weight = 1.0

[[menu.main]]
Name = "Team"
parent = "about_us"
URL = "/about_us/team.md"
Weight = 2.0

[[menu.main]]
Name = "Our Mission"
parent = "about_us"
URL = "/about_us/our_mission.md"
Weight = 3.0

[[menu.main]]
    name = "Awareness Days"
    url  = "/blog/"
    weight = 3

[[menu.main]]
    name = "FAQ"
    identifier = "faq"
    url  = "/faq/"
    weight = 4

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 5

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "httpss://youtube.com/"
    pre = "<i class='fa fa-2x fa-youtube'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "https://facebook.com"
    pre = "<i class='fa fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "https://twitter.com"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:your@email.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

# Enable the contact form by entering your Formspree.io email
[params]
email = "your@email.com"

about_us = "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>"
    copyright = "Copyright (c) 2015 - 2016, YourCompany; all rights reserved."

# Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    address = """<p><strong>Universal Ltd.</strong>
        <br>13/25 New Avenue
        <br>Newtown upon River
        <br>45Y 73J
        <br>England
        <br>
        <strong>Great Britain</strong>
      </p>
      """
    latitude = "-12.043333"
    longitude = "-77.028333"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."